name: disco
description: "Dice Scoring Coordinator"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0-320.0.dev

dependencies:
  color_scheme_display: ^1.0.2
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  test: ^1.31.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Jost
    fonts:
      - asset: fonts/Jost/Jost-VariableFont_wght.ttf
      - asset: fonts/Jost/Jost-Italic-VariableFont_wght.ttf
        style: italic

  
